// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1hmyu9MbAArrQ4sIschaGdrBCS3bPXNs',
    appId: '1:781744579644:web:5492f97f4b37904c40cf39',
    messagingSenderId: '781744579644',
    projectId: 'nexora-pos-system',
    authDomain: 'nexora-pos-system.firebaseapp.com',
    storageBucket: 'nexora-pos-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkEpbRVixRfq1Z5Yf1LgnljWqfjPgYhhA',
    appId: '1:781744579644:android:f812fcbc3c7ce10240cf39',
    messagingSenderId: '781744579644',
    projectId: 'nexora-pos-system',
    storageBucket: 'nexora-pos-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4gG7jUbQBZS81Uxl4HOW8ARDgHsSw9yo',
    appId: '1:781744579644:ios:bb641446826824cd40cf39',
    messagingSenderId: '781744579644',
    projectId: 'nexora-pos-system',
    storageBucket: 'nexora-pos-system.firebasestorage.app',
    iosBundleId: 'com.nexora.nexora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1hmyu9MbAArrQ4sIschaGdrBCS3bPXNs',
    appId: '1:781744579644:web:b88abfce7c4b27b340cf39',
    messagingSenderId: '781744579644',
    projectId: 'nexora-pos-system',
    authDomain: 'nexora-pos-system.firebaseapp.com',
    storageBucket: 'nexora-pos-system.firebasestorage.app',
  );
}
